{% set name = "traceback2" %}
{% set version = "1.4.0" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_val = "05acc67a09980c2ecfedd3423f7ae0104839eccb55fc645773e1caa0951c3030" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash_val }}

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python >=3.6
    - pip
    - pbr

  run:
    - python >=3.6
    - linecache2
    - six

test:
  imports:
    - traceback2

about:
  home: https://github.com/testing-cabal/traceback2
  license: PSF-2.0
  license_file: LICENSE
  summary: 'Backports of the traceback module'
  dev_url: https://github.com/testing-cabal/traceback2

extra:
  recipe-maintainers:
    - pmlandwehr
    - anguslees
    - Tobias-Fischer
