{%set name = "traceback2" %}
{%set version = "1.4.0" %}
{%set hash_type = "sha256" %}
{%set hash_val = "05acc67a09980c2ecfedd3423f7ae0104839eccb55fc645773e1caa0951c3030" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
    - pbr

  run:
    - python
    - linecache2
    - six

test:
  imports:
    - traceback2

about:
  home: https://github.com/testing-cabal/traceback2
  license: PSF 2.0
  # license_file: No explicit MANIFEST, so must omit this for now.
  # see https://github.com/testing-cabal/traceback2/issues/9
  summary: 'Backports of the traceback module'

extra:
  recipe-maintainers:
    - pmlandwehr
    - anguslees
